<a href="https://colab.research.google.com/github/TeAmP0is0N/Hostility-Detection/blob/master/models/BERT_Embeddings_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [ ]:
import pandas as pd
import numpy as np
import pickle
import copy
import re
import matplotlib.pyplot as plt
from sklearn.externals import joblib

from sklearn import preprocessing
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [ ]:
pd.options.display.max_colwidth = 0

In [ ]:
train = pd.read_csv("/gdrive/My Drive/IIITD Fake News Project/Data Set/Constraint 21/Hostility Approach/Complete Dataset/Final Processed Dataset/70-10-20/train.csv")
valid = pd.read_csv("/gdrive/My Drive/IIITD Fake News Project/Data Set/Constraint 21/Hostility Approach/Complete Dataset/Final Processed Dataset/70-10-20/valid.csv")
test  = pd.read_csv("/gdrive/My Drive/IIITD Fake News Project/Data Set/Constraint 21/Hostility Approach/Complete Dataset/Final Processed Dataset/70-10-20/test.csv")

In [ ]:
print(train.shape)
print(valid.shape)
print(test.shape)

(5728, 3)
(811, 3)
(1653, 3)


In [ ]:
train = train.dropna()
valid = valid.dropna()
test  = test.dropna()

print(train.shape)
print(valid.shape)
print(test.shape)

(5728, 3)
(811, 3)
(1653, 3)


In [ ]:
train.head(5)

Unique ID  ...            Labels Set
0  1          ...  hate,offensive      
1  2          ...  non-hostile         
2  3          ...  non-hostile         
3  4          ...  defamation,offensive
4  5          ...  non-hostile         

[5 rows x 3 columns]

In [ ]:
def preprocess(text):
    text = text.lower()
    url = r'http\S+'
    text = re.sub(url, ' ', text, flags=re.MULTILINE)
    emoji = re.compile("["         u"\U0001F600-\U0001F64F"  # emoticons
                                   u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                                   u"\U0001F680-\U0001F6FF"  # transport & map symbols
                                   u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                                   u"\U00002500-\U00002BEF"  # chinese char
                                   u"\U00002702-\U000027B0"
                                   u"\U00002702-\U000027B0"
                                   u"\U000024C2-\U0001F251"
                                   u"\U0001f926-\U0001f937"
                                   u"\U00010000-\U0010ffff"
                                   u"\u2640-\u2642"
                                   u"\u2600-\u2B55"
                                   u"\u200d"
                                   u"\u23cf"
                                   u"\u23e9"
                                   u"\u231a"
                                   u"\ufe0f"  # dingbats
                                   u"\u3030"
                                   "]+", flags=re.UNICODE)
    text =  emoji.sub(r'', text)
    text = ' '.join([word[1:] if word[0] == '#' else word for word in text.split()])

    text = text.split()
    exclude_char_list = ['@','rt','|','%', '[', '(', '{', '}', ']', ')','url','URL']
    text = [word for word in text if all(ch not in word for ch in exclude_char_list)]
    text = ' '.join(text)
    return text

In [ ]:
def assign_labels(text):

    text   = text.split(',')
    labels = [0,0,0,0,0]
    

    for item in text:
        if item=='defamation':
            labels[0] = 1
            break
        
    for item in text:
        if item=='fake':
            labels[1] = 1
            break

    for item in text:
        if item=='hate':
            labels[2] = 1
            break

    for item in text:
        if item=='offensive':
            labels[3] = 1
            break
        
    for item in text:
        if item=='non-hostile':
            labels[4] = 1
            break    
    
    return labels

In [ ]:
def prepare_data(df):
    
    for i in range(len(df)):    
        df.at[i,'Post'] = preprocess(df['Post'][i])
        df.at[i, 'Labels Set'] = assign_labels(df['Labels Set'][i])

    return df


In [ ]:
train = prepare_data(train)
valid = prepare_data(valid)
test  = prepare_data(test)

print(train.shape)
print(valid.shape)
print(test.shape)

(5728, 3)
(811, 3)
(1653, 3)


In [ ]:
train = train.append(valid)
train

Unique ID  ...       Labels Set
0    1          ...  [0, 0, 1, 1, 0]
1    2          ...  [0, 0, 0, 0, 1]
2    3          ...  [0, 0, 0, 0, 1]
3    4          ...  [1, 0, 0, 1, 0]
4    5          ...  [0, 0, 0, 0, 1]
..  ..          ...              ...
806  807        ...  [0, 0, 1, 0, 0]
807  808        ...  [1, 0, 0, 0, 0]
808  809        ...  [0, 0, 0, 0, 1]
809  810        ...  [0, 0, 0, 0, 1]
810  811        ...  [0, 1, 0, 0, 0]

[6539 rows x 3 columns]

In [ ]:
train = train.drop(columns='Unique ID', axis =1)
train = train.reset_index(drop=True)
train

Post       Labels Set
0     मेरे देश के हिन्दु बहुत निराले है। कुछ तो पक्के राम भक्त है और कुछ बाबर के साले है जय श्री राम                                                                                                                                                                                                                                                                                   [0, 0, 1, 1, 0]
1     सरकार हमेशा से किसानों की कमाई को बढ़ाने के लिए नई-नई स्कीमें लाती रहती है, ताकि उन पर ज्यादा आर्थिक बोझ न पड़े.                                                                                                                                                                                                                                                                 [0, 0, 0, 0, 1]
2     सुशांत ने जो बिजनेस डील 9 जून को की थी, वो डील दीपेश को सुशांत की हत्या के दिन ही क्यों याद आई? देखिए 'पूछता है भारत' अर्नब के साथ रिपब्लिक भारत पर live :                                                                                                                                                                                                                       [0, 0, 0, 0, 1]
3     साले जेएनयू छाप कमिने लोग हिन्दुओं को यह कहते है की संविधान सबको बराबर अधिकार देता है। सच्चाई यह है कि यह बराबर अधिकार नहीं देता है।                                                                                                                                                                                                                                             [1, 0, 0, 1, 0]
4     unlock4guidelines - अनलॉक-4 के लिए गाइडलाइन्स जारी - 7 सितंबर से देशभर में मेट्रो सेवा शुरु होगी - 21 सितंबर के बाद रैलियों और बाकी फंक्शन में 100 लोगों को इजाजत - कंटेनमेंट जोन में कोई छूट नहीं - सिनेमाहॉल अभी बंद रहेंगे - 9 से 12वीं के छात्र 21 सितंबर के बाद स्कूल जा सकेंगे.                                                                                            [0, 0, 0, 0, 1]
...                                                                                                                                                                                                                                                                                     ...                                                                                                        ...
6534  चंद फेंके हुए टुकड़ों के लिए हमेशा ही देश से गद्दारी को भौंकने तैयार ड्रग्स के नशे में पूरी तरह खोखले हो चुके दाऊद के गुलाम देशद्रोही गद्दार फिल्मी भांडों के भोंकने को भी मीडिया ब्रेकिंग न्यूज़ बना इन दो कौड़ी के बिकाऊ नशेड़ी गद्दार कुत्तों को हीरो बना देती है देश की विडंबना                                                                                              [0, 0, 1, 0, 0]
6535  आँखों ही आँखों में इशारा हो गया बैठे बैठे जीने का सहारा हो गया नज़रों की इस मारक क्षमता को क्या कहगे।                                                                                                                                                                                                                                                                            [1, 0, 0, 0, 0]
6536  औरंगाबाद में फिर धीरे-धीरे पांव पसार रहा कोरोना संक्रमण, पिछले 6 दिनों में मिले इतने नए मरीज bihar corona aurangabad                                                                                                                                                                                                                                                             [0, 0, 0, 0, 1]
6537  बाइस्कोप: कादर के संवादों का कमाल, डिंपल की कलम का धमाल और तीन बत्ती के जग्गू का नाना संग असली बवाल bioscope angaar shashilalnair dimplekapadia                                                                                                                                                                                                                                  [0, 0, 0, 0, 1]
6538  आखिरकार पॉन्डिचेरी विश्वविद्यालय के रामू नाम के भारतीय छात्र न

In [ ]:
train.iloc[5816]

Post          विशेषज्ञ सलाह  
Labels Set    [0, 0, 0, 0, 1]
Name: 5816, dtype: object

## Getting BERT Embeddings

In [ ]:
!pip install sentence_transformers

In [ ]:
from sentence_transformers import SentenceTransformer

bert_cls  = SentenceTransformer('bert-base-nli-cls-token')
bert_mean = SentenceTransformer('bert-base-nli-mean-tokens')

In [ ]:
#Getting BERT CLS Embeddings
train_bert_cls = pd.DataFrame(bert_cls.encode(train['Post']))
test_bert_cls  = pd.DataFrame(bert_cls.encode(test['Post']))

In [ ]:
train_bert_cls = pd.concat([train_bert_cls, train['Labels Set']], axis=1)
test_bert_cls  = pd.concat([test_bert_cls,  test['Labels Set']],  axis=1)

In [ ]:
print(train_bert_cls.shape)
print(test_bert_cls.shape)

(6539, 769)
(1653, 769)


In [ ]:
# #Getting BERT Mean Embeddings
# train_bert_mean = bert_mean.encode(x_train)
# test_bert_mean  = bert_mean.encode(x_test)

In [ ]:
# #Dumping Embedding Features DataFrame

# path_temp = r"/gdrive/My Drive/3rd Sem/MTech CSE 3/Thesis/IIITD Fake News Project/Data Set/Embeddings Datasets/BERT_CLS/train_df.pkl"
# f = open(path_temp,'wb')
# pickle.dump(train_bert_cls,f)
# f.close()


# path_temp = r"/gdrive/My Drive/3rd Sem/MTech CSE 3/Thesis/IIITD Fake News Project/Data Set/Embeddings Datasets/BERT_CLS/test_df.pkl"
# f = open(path_temp,'wb')
# pickle.dump(test_bert_cls,f)
# f.close()

In [ ]:
#Loading Embedding Features DataFrame

path_temp = r"/gdrive/My Drive/IIITD Fake News Project/Data Set/Embeddings Datasets/BERT_CLS/train_df.pkl"
f = open(path_temp,'rb')
train_bert_cls = pickle.load(f)
f.close()

path_temp = r"/gdrive/My Drive/IIITD Fake News Project/Data Set/Embeddings Datasets/BERT_CLS/test_df.pkl"
f = open(path_temp,'rb')
test_bert_cls = pickle.load(f)
f.close()


In [ ]:
train_bert_cls

0         1         2  ...       766       767       Labels Set
0    -0.144744  0.753920 -0.370921  ...  0.589307 -0.206571  [0, 0, 1, 1, 0]
1    -0.519353  0.546359 -0.319189  ...  0.389509 -0.169360  [0, 0, 0, 0, 1]
2    -0.035937  0.593653 -0.028129  ...  0.471125 -0.300663  [0, 0, 0, 0, 1]
3    -0.330956  0.835987 -0.244033  ...  0.759933 -0.158489  [1, 0, 0, 1, 0]
4    -0.572113  0.866568 -0.252675  ...  0.624688  0.062915  [0, 0, 0, 0, 1]
...        ...       ...       ...  ...       ...       ...              ...
6534 -0.619850  0.904501 -0.358889  ...  0.577738  0.005913  [0, 0, 1, 0, 0]
6535 -0.429183  0.838982 -0.389233  ...  0.505355 -0.186225  [1, 0, 0, 0, 0]
6536 -0.352233  0.713499 -0.202983  ...  0.378970 -0.055231  [0, 0, 0, 0, 1]
6537  0.035434  0.671118 -0.723646  ...  0.778060  0.009573  [0, 0, 0, 0, 1]
6538 -0.247870  0.583266 -0.390746  ...  0.654676  0.054280  [0, 1, 0, 0, 0]

[6539 rows x 769 columns]

In [ ]:
test_bert_cls

0         1         2  ...       766       767       Labels Set
0    -0.885904  0.466816 -0.427689  ...  0.497907 -0.237154  [1, 1, 0, 1, 0]
1    -0.328235  0.636561 -0.446008  ...  0.345142 -0.085919  [0, 0, 0, 0, 1]
2    -0.115869  0.732450 -0.470565  ...  0.570322 -0.136338  [0, 0, 1, 0, 0]
3    -0.072765  0.269666 -0.364946  ...  0.400300 -0.316995  [0, 1, 0, 0, 0]
4    -0.520371  0.471309 -0.400060  ...  0.370883 -0.104683  [1, 0, 0, 0, 0]
...        ...       ...       ...  ...       ...       ...              ...
1648 -0.534929  0.277161 -0.291183  ...  0.217818 -0.286020  [0, 0, 0, 0, 1]
1649 -0.592622  0.595726 -0.352413  ...  0.251041 -0.065659  [0, 0, 1, 0, 0]
1650 -0.343328 -0.392122 -0.485045  ... -0.099480 -0.121998  [0, 0, 0, 1, 0]
1651 -0.507022  0.680654 -0.288482  ...  0.608869 -0.196644  [0, 0, 0, 0, 1]
1652 -0.503185  0.799771 -0.586273  ...  0.518930 -0.193929  [0, 0, 0, 0, 1]

[1653 rows x 769 columns]

In [ ]:
def create_multi_label_data(df):

    total_data = []
    for i in range(len(df)):
        sample = []
        labels = df['Labels Set'][i]

        if(labels[0]==1):
            sample.append(1)
        else:
            sample.append(0)


        if(labels[1]==1):
            sample.append(1)
        else:
            sample.append(0)


        if(labels[2]==1):
            sample.append(1)
        else:
            sample.append(0)
        

        if(labels[3]==1):
            sample.append(1)
        else:
            sample.append(0)
        

        if(labels[4]==1):
            sample.append(1)
        else:
            sample.append(0)

        
        total_data.append(sample)
        
    total_data = pd.DataFrame(total_data, columns = ['Defmatation','Fake','Hate','Offensive','Non-Hostile'])
    return total_data

In [ ]:


multi_train = create_multi_label_data(train_bert_cls)
train_bert_cls = train_bert_cls.drop(train_bert_cls.columns[-1],axis=1)
multi_train = pd.concat( [train_bert_cls,multi_train],axis=1)
multi_train



0         1         2  ...  Hate  Offensive  Non-Hostile
0    -0.144744  0.753920 -0.370921  ...  1     1          0          
1    -0.519353  0.546359 -0.319189  ...  0     0          1          
2    -0.035937  0.593653 -0.028129  ...  0     0          1          
3    -0.330956  0.835987 -0.244033  ...  0     1          0          
4    -0.572113  0.866568 -0.252675  ...  0     0          1          
...        ...       ...       ...  ... ..    ..         ..          
6534 -0.619850  0.904501 -0.358889  ...  1     0          0          
6535 -0.429183  0.838982 -0.389233  ...  0     0          0          
6536 -0.352233  0.713499 -0.202983  ...  0     0          1          
6537  0.035434  0.671118 -0.723646  ...  0     0          1          
6538 -0.247870  0.583266 -0.390746  ...  0     0          0          

[6539 rows x 773 columns]

In [ ]:
multi_test = create_multi_label_data(test_bert_cls)
test_bert_cls = test_bert_cls.drop(test_bert_cls.columns[-1],axis=1)
multi_test = pd.concat( [test_bert_cls,multi_test],axis=1)
multi_test

0         1         2  ...  Hate  Offensive  Non-Hostile
0    -0.885904  0.466816 -0.427689  ...  0     1          0          
1    -0.328235  0.636561 -0.446008  ...  0     0          1          
2    -0.115869  0.732450 -0.470565  ...  1     0          0          
3    -0.072765  0.269666 -0.364946  ...  0     0          0          
4    -0.520371  0.471309 -0.400060  ...  0     0          0          
...        ...       ...       ...  ... ..    ..         ..          
1648 -0.534929  0.277161 -0.291183  ...  0     0          1          
1649 -0.592622  0.595726 -0.352413  ...  1     0          0          
1650 -0.343328 -0.392122 -0.485045  ...  0     1          0          
1651 -0.507022  0.680654 -0.288482  ...  0     0          1          
1652 -0.503185  0.799771 -0.586273  ...  0     0          1          

[1653 rows x 773 columns]

In [ ]:
# #Dumping Embedding Features Multi Label DataFrame

# path_temp = r"/gdrive/My Drive/3rd Sem/MTech CSE 3/Thesis/IIITD Fake News Project/Data Set/Embeddings Datasets/BERT_CLS/multi_label_train_df.pkl"
# f = open(path_temp,'wb')
# pickle.dump(multi_train,f)
# f.close()


# path_temp = r"/gdrive/My Drive/3rd Sem/MTech CSE 3/Thesis/IIITD Fake News Project/Data Set/Embeddings Datasets/BERT_CLS/multi_label_test_df.pkl"
# f = open(path_temp,'wb')
# pickle.dump(multi_test,f)
# f.close()

In [ ]:
#Loading Embedding Features DataFrame

path_temp = r"/gdrive/My Drive/IIITD Fake News Project/Data Set/Embeddings Datasets/BERT_CLS/multi_label_train_df.pkl"
f = open(path_temp,'rb')
multi_train = pickle.load(f)
f.close()

path_temp = r"/gdrive/My Drive/IIITD Fake News Project/Data Set/Embeddings Datasets/BERT_CLS/multi_label_test_df.pkl"
f = open(path_temp,'rb')
multi_test = pickle.load(f)
f.close()


In [ ]:
multi_train

0         1         2  ...  Hate  Offensive  Non-Hostile
0    -0.144744  0.753920 -0.370921  ...  1     1          0          
1    -0.519353  0.546359 -0.319189  ...  0     0          1          
2    -0.035937  0.593653 -0.028129  ...  0     0          1          
3    -0.330956  0.835987 -0.244033  ...  0     1          0          
4    -0.572113  0.866568 -0.252675  ...  0     0          1          
...        ...       ...       ...  ... ..    ..         ..          
6534 -0.619850  0.904501 -0.358889  ...  1     0          0          
6535 -0.429183  0.838982 -0.389233  ...  0     0          0          
6536 -0.352233  0.713499 -0.202983  ...  0     0          1          
6537  0.035434  0.671118 -0.723646  ...  0     0          1          
6538 -0.247870  0.583266 -0.390746  ...  0     0          0          

[6539 rows x 773 columns]

In [ ]:
multi_test

0         1         2  ...  Hate  Offensive  Non-Hostile
0    -0.885904  0.466816 -0.427689  ...  0     1          0          
1    -0.328235  0.636561 -0.446008  ...  0     0          1          
2    -0.115869  0.732450 -0.470565  ...  1     0          0          
3    -0.072765  0.269666 -0.364946  ...  0     0          0          
4    -0.520371  0.471309 -0.400060  ...  0     0          0          
...        ...       ...       ...  ... ..    ..         ..          
1648 -0.534929  0.277161 -0.291183  ...  0     0          1          
1649 -0.592622  0.595726 -0.352413  ...  1     0          0          
1650 -0.343328 -0.392122 -0.485045  ...  0     1          0          
1651 -0.507022  0.680654 -0.288482  ...  0     0          1          
1652 -0.503185  0.799771 -0.586273  ...  0     0          1          

[1653 rows x 773 columns]

## Creating Multi-Label Models

##SVM Classifier

In [ ]:
multi_train = np.asarray(multi_train)
multi_test  = np.asarray(multi_test)

x_train = multi_train[:,:-5]
y_train = multi_train[:,-5:]

x_test  = multi_test[:,:-5]
y_test  = multi_test[:,-5:]


print("x_train: ",x_train.shape)
print("y_train",y_train.shape)
print("x_test",x_test.shape)
print("y_test",y_test.shape)

x_train:  (6539, 768)
y_train (6539, 5)
x_test (1653, 768)
y_test (1653, 5)


In [ ]:
# param_grid = {'C': [0.01, 0.1, 1, 10],
#               'gamma': [1,0.1],
#               'kernel': ['rbf','linear']}


# grid = GridSearchCV(SVC(),param_grid,verbose=10)
# grid.fit(x_train,y_train[:,0])
# print(grid.best_params_)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] C=0.01, gamma=1, kernel=rbf .....................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ......... C=0.01, gamma=1, kernel=rbf, score=0.902, total=  35.5s
[CV] C=0.01, gamma=1, kernel=rbf .....................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   35.5s remaining:    0.0s


[CV] ......... C=0.01, gamma=1, kernel=rbf, score=0.902, total=  35.5s
[CV] C=0.01, gamma=1, kernel=rbf .....................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  1.2min remaining:    0.0s


[CV] ......... C=0.01, gamma=1, kernel=rbf, score=0.902, total=  35.4s
[CV] C=0.01, gamma=1, kernel=rbf .....................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:  1.8min remaining:    0.0s


[CV] ......... C=0.01, gamma=1, kernel=rbf, score=0.901, total=  35.4s
[CV] C=0.01, gamma=1, kernel=rbf .....................................


[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:  2.4min remaining:    0.0s


[CV] ......... C=0.01, gamma=1, kernel=rbf, score=0.902, total=  35.4s
[CV] C=0.01, gamma=1, kernel=linear ..................................


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  3.0min remaining:    0.0s


[CV] ...... C=0.01, gamma=1, kernel=linear, score=0.902, total=  12.8s
[CV] C=0.01, gamma=1, kernel=linear ..................................


[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:  3.2min remaining:    0.0s


[CV] ...... C=0.01, gamma=1, kernel=linear, score=0.902, total=  12.5s
[CV] C=0.01, gamma=1, kernel=linear ..................................


[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:  3.4min remaining:    0.0s


[CV] ...... C=0.01, gamma=1, kernel=linear, score=0.902, total=  12.6s
[CV] C=0.01, gamma=1, kernel=linear ..................................


[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:  3.6min remaining:    0.0s


[CV] ...... C=0.01, gamma=1, kernel=linear, score=0.901, total=  12.6s
[CV] C=0.01, gamma=1, kernel=linear ..................................


[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:  3.8min remaining:    0.0s


[CV] ...... C=0.01, gamma=1, kernel=linear, score=0.902, total=  12.5s
[CV] C=0.01, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=0.01, gamma=0.1, kernel=rbf, score=0.902, total=  22.2s
[CV] C=0.01, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=0.01, gamma=0.1, kernel=rbf, score=0.902, total=  22.2s
[CV] C=0.01, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=0.01, gamma=0.1, kernel=rbf, score=0.902, total=  22.1s
[CV] C=0.01, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=0.01, gamma=0.1, kernel=rbf, score=0.901, total=  21.5s
[CV] C=0.01, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=0.01, gamma=0.1, kernel=rbf, score=0.902, total=  22.2s
[CV] C=0.01, gamma=0.1, kernel=linear ................................
[CV] .... C=0.01, gamma=0.1, kernel=linear, score=0.902, total=  12.7s
[CV] C=0.01, gamma=0.1, kernel=linear ................................
[CV] .

[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed: 32.6min finished


{'C': 1, 'gamma': 1, 'kernel': 'rbf'}


In [ ]:
sum(y_train[:,0])

641.0

In [ ]:
defamation_clf = SVC(kernel='rbf',C=1,gamma=1,verbose=True) ### Earlier C=1, gamma=0.01 gave 76% accuracy
defamation_clf.fit(x_train, y_train[:,0])

[LibSVM]

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=True)

In [ ]:
#Dumping the SVM Model
joblib.dump(defamation_clf,r"/gdrive/My Drive/IIITD Fake News Project/Notebooks/Models/SVM BERT Models/defamation.pkl")
defamation_clf = joblib.load(r"/gdrive/My Drive/IIITD Fake News Project/Notebooks/Models/SVM BERT Models/defamation.pkl")

In [ ]:
print("\n\nAccuracy report: ")
predict = defamation_clf.predict(x_test)
print(classification_report(predict,y_test[:,0]))
print(np.unique(predict,return_counts = True))



Accuracy report: 
              precision    recall  f1-score   support

         0.0       1.00      0.90      0.95      1645
         1.0       0.03      0.62      0.06         8

    accuracy                           0.90      1653
   macro avg       0.51      0.76      0.50      1653
weighted avg       0.99      0.90      0.94      1653

(array([0., 1.]), array([1645,    8]))


## Fake Model

In [ ]:
fake_clf = SVC(kernel='rbf',C=1,gamma=1,verbose=True) ### Earlier C=1, gamma=0.01 gave 76% accuracy
fake_clf.fit(x_train, y_train[:,1])

[LibSVM]

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=True)

In [ ]:
#Dumping the SVM Model
joblib.dump(defamation_clf,r"/gdrive/My Drive/IIITD Fake News Project/Notebooks/Models/SVM BERT Models/fake.pkl")
defamation_clf = joblib.load(r"/gdrive/My Drive/IIITD Fake News Project/Notebooks/Models/SVM BERT Models/fake.pkl")

In [ ]:
print("\n\nAccuracy report: ")
predict = fake_clf.predict(x_test)
print(classification_report(predict,y_test[:,1]))
print(np.unique(predict,return_counts = True))



Accuracy report: 
              precision    recall  f1-score   support

         0.0       1.00      0.80      0.89      1644
         1.0       0.02      0.89      0.05         9

    accuracy                           0.80      1653
   macro avg       0.51      0.85      0.47      1653
weighted avg       0.99      0.80      0.89      1653

(array([0., 1.]), array([1644,    9]))


In [ ]:
pip install scikit-multilearn

     |████████████████████████████████| 92kB 4.2MB/s 


In [ ]:
# Import BinaryRelevance from skmultilearn
from skmultilearn.problem_transform import BinaryRelevance

# Import SVC classifier from sklearn
from sklearn.svm import SVC

# Setup the classifier
classifier = BinaryRelevance(classifier=SVC(), require_dense=[False,True])

# Train
classifier.fit(x_train, y_train)
# Predict
y_pred = classifier.predict(x_test)

In [ ]:
print(y_pred[39])

  (0, 4)	1.0


In [ ]:
from skmultilearn.adapt import MLkNN 

mlknn_classifier = MLkNN() 
mlknn_classifier.fit(x_train,y_train) 


MLkNN(ignore_first_neighbours=0, k=10, s=1.0)

In [ ]:
y_pred = mlknn_classifier.predict(x_test) 
print(y_pred.toarray())

[[0 0 0 0 1]
 [0 0 0 0 1]
 [0 1 0 0 0]
 ...
 [0 0 0 1 0]
 [0 0 0 0 1]
 [1 0 0 1 0]]


In [ ]:
y_pred.shape

(1653, 5)

In [ ]:
from sklearn.metrics import f1_score, precision_score, recall_score,accuracy_score
from sklearn.metrics import classification_report


r  = recall_score(y_true=y_test, y_pred=y_pred, average='weighted')

p  = precision_score(y_true=y_test, y_pred=y_pred, average='weighted')

f1 = f1_score(y_true=y_test, y_pred=y_pred, average='weighted')

# print(p)
# print(r)
# print(f1)
# print(accuracy_score(y_test,y_pred))
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.27      0.10      0.15       169
           1       0.41      0.19      0.26       334
           2       0.36      0.13      0.19       234
           3       0.39      0.29      0.33       219
           4       0.77      0.80      0.78       873

   micro avg       0.63      0.48      0.54      1829
   macro avg       0.44      0.30      0.34      1829
weighted avg       0.56      0.48      0.50      1829
 samples avg       0.51      0.51      0.51      1829



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
